<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://www.example.org/Main002/"
    name="Main002"
	targetNamespace="http://www.example.org/Main002/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl1="http://www.example.org/Import001/">
	
	<!-- Used Import -->
	
	<wsdl:import namespace="http://www.example.org/Import001/"
		location="Import001.wsdl">
	</wsdl:import>
	
	<wsdl:service name="MainService">
		<wsdl:port name="NewPort" binding="wsdl1:Import001SOAP">
			<soap:address location="http://www.example.org/"></soap:address>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
