<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://www.example.org/Main005/"
    name="Main005"
   	xmlns:wsdl1="http://www.example.org/Import001/"
	targetNamespace="http://www.example.org/Main005/">

	<!-- Unused Import -->
	
	<import namespace="http://www.example.org/Import001/"
		location="Import001.wsdl">
	</import>
</definitions>
