<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://www.example.org/Main006/"
    name="Main006"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   	xmlns:wsdl1="http://www.example.org/Import001/"
	targetNamespace="http://www.example.org/Main006/">

	<!-- Used Import -->
	
	<import namespace="http://www.example.org/Import001/"
		location="Import001.wsdl">
	</import>
	
	<service name="MainService">
		<port name="NewPort" binding="wsdl1:Import001SOAP">
			<soap:address location="http://www.example.org/"></soap:address>
		</port>
	</service>
</definitions>
