<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://www.example.org/Main009/"
	name="Main009"
	targetNamespace="http://www.example.org/Main009/">
	
	<!-- Unused Invalid Import -->
	
	<wsdl:import namespace="http://www.example.org/FileNotFound/"
		location="WSDLFileNotFound.wsdl">
	</wsdl:import>
</wsdl:definitions>
